apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: hello-taskrun
spec:
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: hello-task
  workspaces:
    - name: runner-dir
      persistentVolumeClaim:
        claimName: shared-workspace