apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: compliance-pipeline-run
spec:
  pipelineRef:
    name: compliance-pipeline
  params:
  - name: namespace
    value: pipelines-tutorial
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---