---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: moderate-compliance-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: namespace
      type: string
  tasks:
    - name: compliance-subscription
      taskRef:
        name: compliance-subscription-task
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: namespace
          value: $(params.namespace)
    - name: pipeline-subscription
      taskRef:
        name: pipeline-subscription-task
      runAfter:
        - compliance-subscription
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: namespace
          value: $(params.namespace)
    - name: moderate-platform-compliance-suite
      taskRef:
        name: compliance-suite-task
      runAfter:
        - pipeline-subscription
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: namespace
          value: $(params.namespace)
        - name: scanProfile
          value: "xccdf_org.ssgproject.content_profile_moderate"
        - name: scanContent
          value: ssg-ocp4-ds.xml
        - name: scanType
          value: Platform
        - name: scanName
          value: moderate-platform
    - name: moderate-node-compliance-suite
      taskRef:
        name: compliance-suite-task
      runAfter:
        - moderate-platform-compliance-suite
      workspaces:
      - name: source
        workspace: shared-workspace
      params:
      - name: namespace
        value: $(params.namespace)
      - name: scanProfile
        value: "xccdf_org.ssgproject.content_profile_moderate"
      - name: scanContent
        value: ssg-rhcos4-ds.xml
      - name: scanType
        value: Node
      - name: scanName
        value: moderate-node
---